<?php

namespace App\Services\Admin;

use Backpack\CRUD\app\Library\Uploaders\MultipleFiles;
use Illuminate\Database\Eloquent\Model;

class FileUploader extends MultipleFiles
{
    public function uploadFiles(Model $entry, $value = null)
    {
        dd('asd');
        return parent::uploadFiles($entry, $value); // TODO: Change the autogenerated stub
    }


}
